# Generated by Django 3.2.7 on 2021-10-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=250, verbose_name='Address')),
                ('Price', models.IntegerField()),
                ('Bedrooms', models.IntegerField()),
                ('City', models.CharField(max_length=250, verbose_name='City')),
                ('Date', models.DateTimeField()),
                ('PostalCode', models.CharField(max_length=20, verbose_name='Postal Code')),
            ],
        ),
    ]
