# Generated by Django 3.2.7 on 2021-10-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
